GET http://localhost:8080/contacts/
###
GET http://localhost:8080/contacts/63c32f3450b8dc0f22444a01
###
GET http://localhost:8080/contacts/63c32f3450b8dc0f22444a02
###
GET http://localhost:8080/contacts/63c32f3450b8dc0f22444a03
###

# PRODUCTION deploy
GET https://aarontest.onrender.com/contacts/
###
GET https://aarontest.onrender.com/contacts/63c32f3450b8dc0f22444a01
###
GET https://aarontest.onrender.com/contacts/63c32f3450b8dc0f22444a02
###
GET https://aarontest.onrender.com/contacts/63c32f3450b8dc0f22444a03